name = "redgifs-downloader-api"
main = "worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "redgifs-downloader-api"
routes = [
  { pattern = "api.redgifsdownloader.top/*", zone_name = "redgifsdownloader.top" }
]

[env.development]
name = "redgifs-downloader-api-dev"
