name = "redgifs-downloader"
main = "worker.js"
compatibility_date = "2024-01-01"

[assets]
directory = "./out"

[env.production]
name = "redgifs-downloader"
routes = [
  { pattern = "api.redgifsdownloader.top/*", zone_name = "redgifsdownloader.top" }
]

[env.development]
name = "redgifs-downloader-api-dev"
