name = "redgifs-downloader"
main = "worker.js"
compatibility_date = "2024-01-01"
build = { command = "npm run build" }

[assets]
directory = "./out"

# 自定义域名路由配置
[[routes]]
pattern = "redgifsdownloader.top/*"
zone_name = "redgifsdownloader.top"
